### ISSUE TITLE
can upgrade to post-HTSlib version of samtools and bcftools, here on github

### ISSUE THREAD

**Issue by ybolon-nmdp** [nmdp-bioinformatics/pipeline#32]

**Comment by mheuer-nmdp** [comment]
I don't believe homebrew-science is currently the source of bcftools and samtools in the private cloud or on AWS, so they are mostly likely out of date.

If we were to update to version 1.1 or later, process_fastq.sh would need to change to something similar to
https://github.com/nmdp-bioinformatics/flow/blob/master/assemble.nf#L87
https://github.com/nmdp-bioinformatics/flow/blob/master/assemble.nf#L120
