### ISSUE TITLE
Suggest allowing user to specify reference region in place of default full genome reference.

### ISSUE THREAD

**Issue by ybolon-nmdp** [nmdp-bioinformatics/pipeline#44]

**Comment by mheuer-nmdp** [comment]
Can we mark this issue as WontFix?

**Comment by ybolon-nmdp** [comment]
That's fine, I can modify as needed in the bash script and likely best to use the whole genome anyway.

Yung-Tsi Bolon, Ph.D.
Principal Scientist,
Laboratory Services
Laboratory and Biorepository Services
3001 Broadway St. NE Suite 100
Minneapolis, MN 55413
Phone: (612) 351-5742
Cell: (612) 704-1611
Toll Free: 1 (800) 526-7809 Ext 5742
National Marrow Donor Program
BeTheMatch.org<http://BeTheMatch.org>



On Jan 14, 2015, at 3:51 PM, Michael Heuer (NMDP) <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we mark this issue as WontFix?

**Comment by mheuer-nmdp** [comment]
Thanks, closing as WontFix
