### ISSUE TITLE
Have to index all_chr.fa.gz

### ISSUE THREAD

**Issue by ckennedy-nmdp** [nmdp-bioinformatics/pipeline#60]
bwa index /opt/data/tutorial/grch38_fasta_reference/all_chr.fa.gz

**Comment by mheuer-nmdp** [comment]
Can we close this issue now?

**Comment by ckennedy-nmdp** [comment]
Yes

**Comment by mheuer-nmdp** [comment]
Fixed by pull request #102 and #103
