### ISSUE TITLE
Use reference sequences from GRCh38 instead of all_chr.fa

### ISSUE THREAD

**Issue by mheuer-nmdp** [nmdp-bioinformatics/pipeline#61]
Consider using reference sequences directly from GRCh38.  In the ftp link

ftp://ftp.ncbi.nlm.nih.gov/genbank/genomes/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/

a full analysis gzipped FASTA file, no_alt analysis gzipped FASTA file, and tar gzipped bwa indices are available.

See also issue #60

**Comment by mheuer-nmdp** [comment]
Can we close this issue now?

**Comment by ckennedy-nmdp** [comment]
Yes

**Comment by mheuer-nmdp** [comment]
Fixed by pull request #102 and #103
