### ISSUE TITLE
sorted read bam indexing step specifies incorrect file name in process_fastq.bash line 155

### ISSUE THREAD

**Issue by gturenchalk** [nmdp-bioinformatics/pipeline#71]
In process_fastq.bash line 155, where the sorted read bam file is supposed to be indexed, I believe the command should explicitly refer to the full bam file name "${final}.reads.bwa.sorted.bam" rather than "${final}.reads.bwa.sorted"  because when I run the code I get errors along the lines of:

+ samtools index ./tutorialTest4/final/454Reads.MID13.fastq.reads.bwa.sorted
[E::hts_open] fail to open file './tutorialTest4/final/454Reads.MID13.fastq.reads.bwa.sorted'

process_fastq.bash
153   bwa bwasw ${REFDIR}/${REFCHR} ${intermediate}.ssake.contigs | samtools view -Sb - | samtools sort - ${final}.contigs.bwa.sorted
154   bwa mem ${REFDIR}/${REFCHR} ${FILE1} ${FILE2} | samtools view -Sb - | samtools sort - ${final}.reads.bwa.sorted
155  samtools index ${final}.reads.bwa.sorted
156  samtools mpileup -RB -C 0 -Q 0 -f ${REFDIR}/${REFCHR}.gz ${final}.contigs.bwa.sorted.bam | cat $BOILERPLATE_HEADER - | bcftools view -O z -o ${final}.vcf.gz
157   samtools mpileup -f ${REFDIR}/${REFCHR}.gz ${final}.reads.bwa.sorted.bam > ${final}.reads.bwa.sorted.vcf

**Comment by mheuer-nmdp** [comment]
@janders3-nmdp @ckennedy-nmdp can you look into this?  I think the commit https://github.com/ckennedy-nmdp/pipeline/commit/53abf3e77c82f1f79fc0a475a650795b6377de41 may have fixed this issue as a side effect

**Comment by ckennedy-nmdp** [comment]
Yes, this is fixed

**Comment by mheuer-nmdp** [comment]
Fixed in pull request #102
